/*
*** DO NOT DELETE ***
This file contains editor utilities for analyzing intersections in the Critical Strip.
It includes functions which perform dense sampling of the two paths generated by
RhombusPoints.GetBPSymmetry and RhombusPoints.GetBPForward for a given critical index.

Available Functions:
- TestKnownIntersections: Scans ±0.001 around known t values with fine steps and logs the minimal distance and corresponding points.
- TestPreciseIntersectionValues: Performs a coarse scan followed by a fine scan to densely sample the distance function around each candidate intersection.
- TestExactIntersection: For each known intersection candidate, it zeroes in on the best t value, then uses two points from each path (taken at a small epsilon around the best t)
  to form two line segments. A simple line intersection algorithm is used to compute the exact intersection point of these lines,
  approximating the true intersection as closely as double precision allows.

The goal is to investigate and determine the true intersection values despite small numerical offsets.
*** END OF DO NOT DELETE HEADER ***
*/

using UnityEngine;
using UnityEditor;
using System.IO;
using System.Collections.Generic;
using System.Text;

public static class FindIntersections
{
    private const double MIN_INDEX = 4.0;
    private const double MAX_INDEX = 6.0;
    private const double INDEX_STEP = 0.01;
    
    private const int POINTS_PER_PATH = 10000; // 100x more points than BPSymmetryRenderer
    
    // Known critical value that should have exactly 3 intersections
    private static readonly double CRITICAL_INDEX = 5.108561515808110;

    [MenuItem("Critical Strip/Find Rhombus Intersections")]
    public static void FindRhombusIntersections()
    {
        var intersectionData = new List<(double real, double index, Vector2 point)>();
        
        // First check the known critical value with high resolution
        Debug.Log($"Checking critical index value: {CRITICAL_INDEX:F15}");
        FindIntersectionsForIndex(CRITICAL_INDEX, intersectionData);
        
        // Then check the range with regular steps
        int totalSteps = (int)System.Math.Ceiling((MAX_INDEX - MIN_INDEX) / INDEX_STEP);
        int currentStep = 0;

        for (double index = MIN_INDEX; index <= MAX_INDEX; index += INDEX_STEP)
        {
            if (Mathf.Abs((float)(index - CRITICAL_INDEX)) < INDEX_STEP)
            {
                Debug.Log($"Skipping {index:F15} as it's close to critical value");
                continue;
            }
            
            if (EditorUtility.DisplayCancelableProgressBar(
                "Finding Intersections",
                $"Processing index {index:F15}",
                (float)currentStep / totalSteps))
            {
                EditorUtility.ClearProgressBar();
                Debug.Log("Intersection finding cancelled.");
                return;
            }

            FindIntersectionsForIndex(index, intersectionData);
            currentStep++;
        }

        EditorUtility.ClearProgressBar();
        SaveToCSV(intersectionData);
    }

    private static void FindIntersectionsForIndex(double index, List<(double real, double index, Vector2 point)> intersectionData)
    {
        var path1 = new Vector2[POINTS_PER_PATH];
        var path2 = new Vector2[POINTS_PER_PATH];
        
        // Generate paths with higher resolution
        for (int i = 0; i < POINTS_PER_PATH; i++)
        {
            double r = (double)i / POINTS_PER_PATH;
            path1[i] = RhombusPoints.GetBPSymmetry((float)r, (float)index);
            path2[i] = RhombusPoints.GetBPForward((float)r, (float)index);
        }
        
        var intersections = FindPathIntersections(path1, path2);
        Debug.Log($"Found {intersections.Length} intersections for index {index:F15}");
        
        foreach (var intersection in intersections)
        {
            // Find closest point in either path to get real value
            double closestDist = double.MaxValue;
            double closestReal = 0.0;
            
            for (int i = 0; i < path1.Length; i++)
            {
                double dist = Vector2.Distance(path1[i], intersection);
                if (dist < closestDist)
                {
                    closestDist = dist;
                    closestReal = (double)i / POINTS_PER_PATH;
                }
            }
            
            for (int i = 0; i < path2.Length; i++)
            {
                double dist = Vector2.Distance(path2[i], intersection);
                if (dist < closestDist)
                {
                    closestDist = dist;
                    closestReal = (double)i / POINTS_PER_PATH;
                }
            }
            
            intersectionData.Add((closestReal, index, intersection));
        }
    }

    private static Vector2[] FindPathIntersections(Vector2[] path1, Vector2[] path2)
    {
        var intersections = new List<Vector2>();
        
        // Check each line segment pair for intersections
        for (int i = 1; i < path1.Length; i++)
        {
            var line1Start = path1[i - 1];
            var line1End = path1[i];
            
            for (int j = 1; j < path2.Length; j++)
            {
                var line2Start = path2[j - 1];
                var line2End = path2[j];
                
                if (TryGetLineIntersection(line1Start, line1End, line2Start, line2End, out Vector2 intersection))
                {
                    intersections.Add(intersection);
                }
            }
        }
        
        return intersections.ToArray();
    }

    private static bool TryGetLineIntersection(Vector2 line1Start, Vector2 line1End, Vector2 line2Start, Vector2 line2End, out Vector2 intersection)
    {
        intersection = Vector2.zero;

        double a1 = line1End.y - line1Start.y;
        double b1 = line1Start.x - line1End.x;
        double c1 = a1 * line1Start.x + b1 * line1Start.y;

        double a2 = line2End.y - line2Start.y;
        double b2 = line2Start.x - line2End.x;
        double c2 = a2 * line2Start.x + b2 * line2Start.y;

        double determinant = a1 * b2 - a2 * b1;

        if (System.Math.Abs(determinant) < 1e-10)
            return false;

        double x = (b2 * c1 - b1 * c2) / determinant;
        double y = (a1 * c2 - a2 * c1) / determinant;
        intersection = new Vector2((float)x, (float)y);

        return IsPointOnLineSegment(line1Start, line1End, intersection) &&
               IsPointOnLineSegment(line2Start, line2End, intersection);
    }

    private static bool IsPointOnLineSegment(Vector2 lineStart, Vector2 lineEnd, Vector2 point)
    {
        double d1 = Vector2.Distance(lineStart, point);
        double d2 = Vector2.Distance(lineEnd, point);
        double lineLength = Vector2.Distance(lineStart, lineEnd);
        double buffer = 1e-10;

        return d1 + d2 >= lineLength - buffer && d1 + d2 <= lineLength + buffer;
    }

    private static void SaveToCSV(List<(double real, double index, Vector2 point)> intersections)
    {
        var csv = new StringBuilder();
        csv.AppendLine("real,index");
        
        foreach (var (real, index, _) in intersections)
        {
            csv.AppendLine($"{real:F15},{index:F15}");
        }
        
        string path = "Assets/Resources/intersections.csv";
        Directory.CreateDirectory(Path.GetDirectoryName(path));
        File.WriteAllText(path, csv.ToString());
        AssetDatabase.Refresh();
    }

    [MenuItem("Critical Strip/Test Known values for intersection")]
    public static void TestKnownIntersections()
    {
        // Known intersection values to test
        double[] knownValues = { 0.078987, 0.500029, 0.921013 };
        double scanRange = 0.001; // Scan ±0.001 around each known value
        double stepSize = 0.0000001; // Use even finer steps
        
        var results = new StringBuilder();
        results.AppendLine("=== Known Intersection Values Analysis ===");
        results.AppendLine($"Critical Index: {CRITICAL_INDEX:F15}");
        results.AppendLine("Scanning ±0.001 with step size 0.000001");
        results.AppendLine();
        
        foreach (double knownT in knownValues)
        {
            Debug.Log($"\nTesting around known intersection t={knownT:F15}");
            double minDistance = double.MaxValue;
            double bestT = knownT;
            
            // Scan around the known value
            for (double t = knownT - scanRange; t <= knownT + scanRange; t += stepSize)
            {
                Vector2 p1 = RhombusPoints.GetBPSymmetry((float)t, (float)CRITICAL_INDEX);
                Vector2 p2 = RhombusPoints.GetBPForward((float)t, (float)CRITICAL_INDEX);
                double distance = Vector2.Distance(p1, p2);
                
                if (distance < minDistance)
                {
                    minDistance = distance;
                    bestT = t;
                }
            }
            
            // Get the points at the best t value for detailed output
            Vector2 bestP1 = RhombusPoints.GetBPSymmetry((float)bestT, (float)CRITICAL_INDEX);
            Vector2 bestP2 = RhombusPoints.GetBPForward((float)bestT, (float)CRITICAL_INDEX);
            
            results.AppendLine($"Known t = {knownT:F15}");
            results.AppendLine($"Best t found = {bestT:F15}");
            results.AppendLine($"Minimum distance = {minDistance:E15}");
            results.AppendLine($"Symmetry point = ({bestP1.x:F6}, {bestP1.y:F6})");
            results.AppendLine($"Forward point = ({bestP2.x:F6}, {bestP2.y:F6})");
            results.AppendLine($"Difference from known = {System.Math.Abs(bestT - knownT):E15}");
            results.AppendLine();
        }
        
        Debug.LogWarning(results.ToString());
    }

    [MenuItem("Critical Strip/Test Precise Intersection Values")]
    public static void TestPreciseIntersectionValues()
    {
        // Known intersection values to test (using the updated known values from the renderer)
        double[] knownValues = { 0.079987, 0.500029, 0.920013 };
        
        // Coarse scan parameters
        double coarseScanRange = 0.001;    // ±0.001 around the known value
        double coarseStep = 0.0000001;     // Coarse step size: 1e-7
        
        // Fine scan parameters
        double fineScanRange = 0.00001;      // ±0.00001 around the coarse best value
        double fineStep = 0.00000001;        // Fine step size: 1e-8
        
        var consolidatedLog = new StringBuilder();
        consolidatedLog.AppendLine("=== Precise Intersection Values Analysis ===");
        consolidatedLog.AppendLine($"Critical Index: {CRITICAL_INDEX:F15}");
        consolidatedLog.AppendLine();
        
        foreach (double knownT in knownValues)
        {
            consolidatedLog.AppendLine($"--- Analysis for Known t = {knownT:F15} ---");
            
            // Coarse scan: find preliminary best t
            double bestT_coarse = knownT;
            double minDist_coarse = double.MaxValue;
            for (double t = knownT - coarseScanRange; t <= knownT + coarseScanRange; t += coarseStep)
            {
                Vector2 sp = RhombusPoints.GetBPSymmetry((float)t, (float)CRITICAL_INDEX);
                Vector2 fp = RhombusPoints.GetBPForward((float)t, (float)CRITICAL_INDEX);
                double dist = Vector2.Distance(sp, fp);
                if (dist < minDist_coarse)
                {
                    minDist_coarse = dist;
                    bestT_coarse = t;
                }
            }
            consolidatedLog.AppendLine($"Coarse Scan: Best t = {bestT_coarse:F15}, distance = {minDist_coarse:E15}");
            consolidatedLog.AppendLine();
            
            // Fine scan: more densely sample around bestT_coarse
            double bestT_fine = bestT_coarse;
            double minDist_fine = double.MaxValue;
            var fineScanLog = new StringBuilder();
            fineScanLog.AppendLine("t, distance, symmetry_x, symmetry_y, forward_x, forward_y");
            for (double t = bestT_coarse - fineScanRange; t <= bestT_coarse + fineScanRange; t += fineStep)
            {
                Vector2 sp = RhombusPoints.GetBPSymmetry((float)t, (float)CRITICAL_INDEX);
                Vector2 fp = RhombusPoints.GetBPForward((float)t, (float)CRITICAL_INDEX);
                double dist = Vector2.Distance(sp, fp);
                if (dist < minDist_fine)
                {
                    minDist_fine = dist;
                    bestT_fine = t;
                }
                fineScanLog.AppendLine($"{t:F15}, {dist:E15}, {sp.x:F6}, {sp.y:F6}, {fp.x:F6}, {fp.y:F6}");
            }
            consolidatedLog.AppendLine($"Fine Scan: Best t = {bestT_fine:F15}, distance = {minDist_fine:E15}");
            consolidatedLog.AppendLine("Detailed Dense Sampling Data:");
            consolidatedLog.Append(fineScanLog.ToString());
            consolidatedLog.AppendLine();
        }
        Debug.LogWarning(consolidatedLog.ToString());
    }

    [MenuItem("Critical Strip/Test Exact Intersection")]
    public static void TestExactIntersection()
    {
        // Known intersection values to test (using the updated known values from the renderer)
        double[] knownValues = { 0.079987, 0.500029, 0.920013 };
        // Epsilon for sampling around best t - increased from 1e-6 to 1e-5 for better line segment conditioning
        double epsilon = 1e-5;
        // Fine scan parameters for zeroing in
        double fineScanRange = 0.00001;      // ±0.00001 around the known value
        double fineStep = 0.00000001;        // Fine step size: 1e-8

        var log = new StringBuilder();
        log.AppendLine("=== Exact Intersection Analysis ===");
        log.AppendLine($"Critical Index: {CRITICAL_INDEX:F15}");
        log.AppendLine();

        foreach (double knownT in knownValues)
        {
            // Fine scan: densely sample around the known value to find the best t value
            double bestT = knownT;
            double minDist = double.MaxValue;
            for (double t = knownT - fineScanRange; t <= knownT + fineScanRange; t += fineStep)
            {
                Vector2 sp = RhombusPoints.GetBPSymmetry((float)t, (float)CRITICAL_INDEX);
                Vector2 fp = RhombusPoints.GetBPForward((float)t, (float)CRITICAL_INDEX);
                double d = Vector2.Distance(sp, fp);
                if (d < minDist)
                {
                    minDist = d;
                    bestT = t;
                }
            }
            
            // Using a larger epsilon, get two points from each function around bestT
            Vector2 symmetryPoint1 = RhombusPoints.GetBPSymmetry((float)(bestT - epsilon), (float)CRITICAL_INDEX);
            Vector2 symmetryPoint2 = RhombusPoints.GetBPSymmetry((float)(bestT + epsilon), (float)CRITICAL_INDEX);
            Vector2 forwardPoint1 = RhombusPoints.GetBPForward((float)(bestT - epsilon), (float)CRITICAL_INDEX);
            Vector2 forwardPoint2 = RhombusPoints.GetBPForward((float)(bestT + epsilon), (float)CRITICAL_INDEX);
            
            // Compute line intersection between the line segments defined by these points
            Vector2 intersectionPoint;
            bool intersected = TryGetLineIntersection(symmetryPoint1, symmetryPoint2, forwardPoint1, forwardPoint2, out intersectionPoint);
            
            log.AppendLine($"For known t = {knownT:F15}:");
            log.AppendLine($"Best t found = {bestT:F15} with minimal distance = {minDist:E15}");
            log.AppendLine($"Symmetry points: ({symmetryPoint1.x:F6}, {symmetryPoint1.y:F6}) to ({symmetryPoint2.x:F6}, {symmetryPoint2.y:F6})");
            log.AppendLine($"Forward points:  ({forwardPoint1.x:F6}, {forwardPoint1.y:F6}) to ({forwardPoint2.x:F6}, {forwardPoint2.y:F6})");
            if (intersected)
            {
                log.AppendLine($"Exact intersection computed at: ({intersectionPoint.x:F6}, {intersectionPoint.y:F6})");
            }
            else
            {
                log.AppendLine("Line segments did not intersect in the approximate linear region.");
            }
            log.AppendLine();
        }
        Debug.LogWarning(log.ToString());
    }
} 