/*
*** DO NOT DELETE ***
This file contains editor utilities for analyzing intersections in the Critical Strip.
It includes functions which perform dense sampling of the two paths generated by
RhombusPoints.GetBPSymmetry and RhombusPoints.GetBPForward for a given critical index.

Available Functions:
- TestKnownIntersections: Scans ±0.001 around known t values with fine steps and logs the minimal distance and corresponding points.
- TestPreciseIntersectionValues: Performs a coarse scan followed by a fine scan to densely sample the distance function around each candidate intersection.
- TestExactIntersection: For each known intersection candidate, it zeroes in on the best t value, then uses two points from each path (taken at a small epsilon around the best t)
  to form two line segments. A simple line intersection algorithm is used to compute the exact intersection point of these lines,
  approximating the true intersection as closely as double precision allows.

The goal is to investigate and determine the true intersection values despite small numerical offsets.
*** END OF DO NOT DELETE HEADER ***
*/

using UnityEngine;
using UnityEditor;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System;

public static class FindIntersections
{
    private const double MIN_INDEX = 1.0;
    private const double MAX_INDEX = 11.0;
    private const double INDEX_STEP = 0.0001;
    
    private const int POINTS_PER_PATH = 10000; // 100x more points than BPSymmetryRenderer
    
    // Known critical value that should have exactly 3 intersections
    private static readonly double CRITICAL_INDEX = 5.108561515808110;

    [MenuItem("Critical Strip/Find Rhombus Intersections")]
    public static void FindRhombusIntersections()
    {
        var intersectionData = new List<(double real, double index, Vector2 point)>();

        // Then check the range with regular steps
        int totalSteps = (int)System.Math.Ceiling((MAX_INDEX - MIN_INDEX) / INDEX_STEP);
        int currentStep = 0;

        for (double index = MIN_INDEX; index <= MAX_INDEX; index += INDEX_STEP)
        {
            if (EditorUtility.DisplayCancelableProgressBar(
                "Finding Intersections",
                $"Processing index {index:F15}",
                (float)currentStep / totalSteps))
            {
                EditorUtility.ClearProgressBar();
                Debug.Log("Intersection finding cancelled.");
                return;
            }

            // FindIntersectionsUniformForIndex(index, intersectionData);
            FindSymmetricIntersections(index, intersectionData);
            currentStep++;
        }

        EditorUtility.ClearProgressBar();
        SaveToCSV(intersectionData);
    }

    [MenuItem("Critical Strip/Find Rhombus Angle Zero Points")]
    public static void FindRhombusAngleZeroPoints()
    {
        var AnglePointsData = new List<(double real, double index, Vector2 point)>();
        
        // Then check the range with regular steps
        int totalSteps = (int)System.Math.Ceiling((MAX_INDEX - MIN_INDEX) / INDEX_STEP);
        int currentStep = 0;

        for (double index = MIN_INDEX; index <= MAX_INDEX; index += INDEX_STEP)
        {
            if (EditorUtility.DisplayCancelableProgressBar(
                "Finding Angle Zero Points",
                $"Processing index {index:F15}",
                (float)currentStep / totalSteps))
            {
                EditorUtility.ClearProgressBar();
                Debug.Log("Intersection finding cancelled.");
                return;
            }

            FindAngleZeroPoints(index, AnglePointsData);
            currentStep++;
        }

        EditorUtility.ClearProgressBar();
        SaveToCSV(AnglePointsData);
    }

    [MenuItem("Critical Strip/Find ThetaTwo")]
    public static void FindThetaTwo()
    {
        var thetaData = new List<(double real, double index, Vector2 point)>();

        int totalSteps = (int)System.Math.Ceiling((MAX_INDEX - MIN_INDEX) / INDEX_STEP);
        int currentStep = 0;

        for (double index = MIN_INDEX; index <= MAX_INDEX; index += INDEX_STEP)
        {
            if (EditorUtility.DisplayCancelableProgressBar(
                "Finding ThetaData",
                $"Processing index {index:F15}",
                (float)currentStep / totalSteps))
            {
                EditorUtility.ClearProgressBar();
                Debug.Log("Theta finding cancelled.");
                return;
            }

            FindThetaData(index, thetaData);
            currentStep++;
        }

        EditorUtility.ClearProgressBar();
        SaveToCSV(thetaData);
    }

    private static void FindThetaData(double index, List<(double real, double index, Vector2 point)> thetaData)
    {
        var twoPI = 2.0*Math.PI;

        
        // // IR intersection angle
        // var r = 0.25;
        // // double ThetaTwo = GetForwardRhombusAngle(((int)r == 2) ? 0.5 : (int)r, index);
        // double ThetaTwo = GetForwardRhombusAngle(r, index);
        // // transform to fit BisectorPoint ThetaAngle
        // if(ThetaTwo < 0)
        //     ThetaTwo += 360;

        // // Convert to radians
        // ThetaTwo = ThetaTwo * Math.PI / 180.0;


        // theta formula
        var ThetaTwo = -BisectorPoint.ThetaTwo(index);

        var phase = (ThetaTwo % twoPI) / twoPI;
        var pt = new Vector(phase, index);
        thetaData.Add((phase, index, pt));
    }

    private static void FindIntersectionsForIndex(double index, List<(double real, double index, Vector2 point)> intersectionData)
    {
        var path1 = new Vector2[POINTS_PER_PATH];
        var path2 = new Vector2[POINTS_PER_PATH];
        
        // Generate paths with higher resolution
        for (int i = 0; i < POINTS_PER_PATH; i++)
        {
            double r = (double)i / POINTS_PER_PATH;
            path1[i] = RhombusPoints.GetBPSymmetry((float)r, (float)index);
            path2[i] = RhombusPoints.GetBPForward((float)r, (float)index);
        }
        
        var intersections = FindPathIntersections(path1, path2);
        Debug.Log($"Found {intersections.Length} intersections for index {index:F15}");
        
        foreach (var intersection in intersections)
        {
            // Find closest point in either path to get real value
            double closestDist = double.MaxValue;
            double closestReal = 0.0;
            
            for (int i = 0; i < path1.Length; i++)
            {
                double dist = Vector2.Distance(path1[i], intersection);
                if (dist < closestDist)
                {
                    closestDist = dist;
                    closestReal = (double)i / POINTS_PER_PATH;
                }
            }
            
            for (int i = 0; i < path2.Length; i++)
            {
                double dist = Vector2.Distance(path2[i], intersection);
                if (dist < closestDist)
                {
                    closestDist = dist;
                    closestReal = (double)i / POINTS_PER_PATH;
                }
            }
            
            intersectionData.Add((closestReal, index, intersection));
        }
    }

    private static Vector2[] FindPathIntersections(Vector2[] path1, Vector2[] path2)
    {
        var intersections = new List<Vector2>();
        
        // Check each line segment pair for intersections
        for (int i = 1; i < path1.Length; i++)
        {
            var line1Start = path1[i - 1];
            var line1End = path1[i];
            
            for (int j = 1; j < path2.Length; j++)
            {
                var line2Start = path2[j - 1];
                var line2End = path2[j];
                
                if (TryGetLineIntersection(line1Start, line1End, line2Start, line2End, out Vector2 intersection))
                {
                    intersections.Add(intersection);
                }
            }
        }
        
        return intersections.ToArray();
    }

    private static bool TryGetLineIntersection(Vector2 line1Start, Vector2 line1End, Vector2 line2Start, Vector2 line2End, out Vector2 intersection)
    {
        intersection = Vector2.zero;

        double a1 = line1End.y - line1Start.y;
        double b1 = line1Start.x - line1End.x;
        double c1 = a1 * line1Start.x + b1 * line1Start.y;

        double a2 = line2End.y - line2Start.y;
        double b2 = line2Start.x - line2End.x;
        double c2 = a2 * line2Start.x + b2 * line2Start.y;

        double determinant = a1 * b2 - a2 * b1;

        if (System.Math.Abs(determinant) < 1e-10)
            return false;

        double x = (b2 * c1 - b1 * c2) / determinant;
        double y = (a1 * c2 - a2 * c1) / determinant;
        intersection = new Vector2((float)x, (float)y);

        return IsPointOnLineSegment(line1Start, line1End, intersection) &&
               IsPointOnLineSegment(line2Start, line2End, intersection);
    }

    private static bool IsPointOnLineSegment(Vector2 lineStart, Vector2 lineEnd, Vector2 point)
    {
        double d1 = Vector2.Distance(lineStart, point);
        double d2 = Vector2.Distance(lineEnd, point);
        double lineLength = Vector2.Distance(lineStart, lineEnd);
        double buffer = 1e-10;

        return d1 + d2 >= lineLength - buffer && d1 + d2 <= lineLength + buffer;
    }

    private static void SaveToCSV(List<(double real, double index, Vector2 point)> dataPoints)
    {
        var csv = new StringBuilder();
        csv.AppendLine("New Data,#8800FF,false,true");
        
        foreach (var (real, index, _) in dataPoints)
        {
            csv.AppendLine($"{real:F15},{index:F15}");
        }
        
        string path = "Assets/Resources/CriticalStripPoints/NewData.csv";
        Directory.CreateDirectory(Path.GetDirectoryName(path));
        File.WriteAllText(path, csv.ToString());
        AssetDatabase.Refresh();
        Debug.Log($"[dataPoints] Saved points to {path}");
    }

    [MenuItem("Critical Strip/Test Known values for intersection")]
    public static void TestKnownIntersections()
    {
        // Known intersection values to test
        double[] knownValues = { 0.078987, 0.500029, 0.921013 };
        double scanRange = 0.001; // Scan ±0.001 around each known value
        double stepSize = 0.0000001; // Use even finer steps
        
        var results = new StringBuilder();
        results.AppendLine("=== Known Intersection Values Analysis ===");
        results.AppendLine($"Critical Index: {CRITICAL_INDEX:F15}");
        results.AppendLine("Scanning ±0.001 with step size 0.000001");
        results.AppendLine();
        
        foreach (double knownT in knownValues)
        {
            Debug.Log($"\nTesting around known intersection t={knownT:F15}");
            double minDistance = double.MaxValue;
            double bestT = knownT;
            
            // Scan around the known value
            for (double t = knownT - scanRange; t <= knownT + scanRange; t += stepSize)
            {
                Vector2 p1 = RhombusPoints.GetBPSymmetry((float)t, (float)CRITICAL_INDEX);
                Vector2 p2 = RhombusPoints.GetBPForward((float)t, (float)CRITICAL_INDEX);
                double distance = Vector2.Distance(p1, p2);
                
                if (distance < minDistance)
                {
                    minDistance = distance;
                    bestT = t;
                }
            }
            
            // Get the points at the best t value for detailed output
            Vector2 bestP1 = RhombusPoints.GetBPSymmetry((float)bestT, (float)CRITICAL_INDEX);
            Vector2 bestP2 = RhombusPoints.GetBPForward((float)bestT, (float)CRITICAL_INDEX);
            
            results.AppendLine($"Known t = {knownT:F15}");
            results.AppendLine($"Best t found = {bestT:F15}");
            results.AppendLine($"Minimum distance = {minDistance:E15}");
            results.AppendLine($"Symmetry point = ({bestP1.x:F6}, {bestP1.y:F6})");
            results.AppendLine($"Forward point = ({bestP2.x:F6}, {bestP2.y:F6})");
            results.AppendLine($"Difference from known = {System.Math.Abs(bestT - knownT):E15}");
            results.AppendLine();
        }
        
        Debug.LogWarning(results.ToString());
    }

    [MenuItem("Critical Strip/Test Precise Intersection Values")]
    public static void TestPreciseIntersectionValues()
    {
        // Known intersection values to test (using the updated known values from the renderer)
        double[] knownValues = { 0.079987, 0.500029, 0.920013 };
        
        // Coarse scan parameters
        double coarseScanRange = 0.001;    // ±0.001 around the known value
        double coarseStep = 0.0000001;     // Coarse step size: 1e-7
        
        // Fine scan parameters
        double fineScanRange = 0.00001;      // ±0.00001 around the coarse best value
        double fineStep = 0.00000001;        // Fine step size: 1e-8
        
        var consolidatedLog = new StringBuilder();
        consolidatedLog.AppendLine("=== Precise Intersection Values Analysis ===");
        consolidatedLog.AppendLine($"Critical Index: {CRITICAL_INDEX:F15}");
        consolidatedLog.AppendLine();
        
        foreach (double knownT in knownValues)
        {
            consolidatedLog.AppendLine($"--- Analysis for Known t = {knownT:F15} ---");
            
            // Coarse scan: find preliminary best t
            double bestT_coarse = knownT;
            double minDist_coarse = double.MaxValue;
            for (double t = knownT - coarseScanRange; t <= knownT + coarseScanRange; t += coarseStep)
            {
                Vector2 sp = RhombusPoints.GetBPSymmetry((float)t, (float)CRITICAL_INDEX);
                Vector2 fp = RhombusPoints.GetBPForward((float)t, (float)CRITICAL_INDEX);
                double dist = Vector2.Distance(sp, fp);
                if (dist < minDist_coarse)
                {
                    minDist_coarse = dist;
                    bestT_coarse = t;
                }
            }
            consolidatedLog.AppendLine($"Coarse Scan: Best t = {bestT_coarse:F15}, distance = {minDist_coarse:E15}");
            consolidatedLog.AppendLine();
            
            // Fine scan: more densely sample around bestT_coarse
            double bestT_fine = bestT_coarse;
            double minDist_fine = double.MaxValue;
            var fineScanLog = new StringBuilder();
            fineScanLog.AppendLine("t, distance, symmetry_x, symmetry_y, forward_x, forward_y");
            for (double t = bestT_coarse - fineScanRange; t <= bestT_coarse + fineScanRange; t += fineStep)
            {
                Vector2 sp = RhombusPoints.GetBPSymmetry((float)t, (float)CRITICAL_INDEX);
                Vector2 fp = RhombusPoints.GetBPForward((float)t, (float)CRITICAL_INDEX);
                double dist = Vector2.Distance(sp, fp);
                if (dist < minDist_fine)
                {
                    minDist_fine = dist;
                    bestT_fine = t;
                }
                fineScanLog.AppendLine($"{t:F15}, {dist:E15}, {sp.x:F6}, {sp.y:F6}, {fp.x:F6}, {fp.y:F6}");
            }
            consolidatedLog.AppendLine($"Fine Scan: Best t = {bestT_fine:F15}, distance = {minDist_fine:E15}");
            consolidatedLog.AppendLine("Detailed Dense Sampling Data:");
            consolidatedLog.Append(fineScanLog.ToString());
            consolidatedLog.AppendLine();
        }
        Debug.LogWarning(consolidatedLog.ToString());
    }

    [MenuItem("Critical Strip/Test Exact Intersection")]
    public static void TestExactIntersection()
    {
        var intersectionData = new List<(double real, double index, Vector2 point)>();
        FindIntersectionsUniformForIndex(CRITICAL_INDEX, intersectionData);
        
        var log = new StringBuilder();
        log.AppendLine("=== Exact Intersection Analysis (Uniform Method) ===");
        log.AppendLine($"Critical Index: {CRITICAL_INDEX:F15}");
        log.AppendLine($"Found {intersectionData.Count} intersections.");
        foreach (var (t, idx, pt) in intersectionData)
        {
            log.AppendLine($"Intersection: t = {t:F15}, index = {idx:F15}, point = ({pt.x:F6}, {pt.y:F6})");
        }
        Debug.LogWarning(log.ToString());
        SaveToCSV(intersectionData);
    }

    // finds points where the angle between bisector legs are zero
    private static void FindAngleZeroPoints(double index, List<(double real, double index, Vector2 point)> angleData)
    {
        const int resolution = 1000;
        double dt = 1.0 / resolution;
        double[] angles = new double[resolution + 1];
        double[] ts = new double[resolution + 1];

        for (int i = 0; i <= resolution; i++)
        {
            double t = i * dt;
            ts[i] = t;
            angles[i] = GetForwardRhombusAngle(t, index);
        }
        
        // find the points where the angle jumps from -180 to 180 or vice versa
        for (int i = 0; i < resolution - 1; i++)
        {
            double d0 = angles[i];
            double d1 = angles[i + 1];
            if (Math.Abs(d0 - d1) > 180)
            {
                double low = ts[i];
                double high = ts[i + 1];
                for (int iter = 0; iter < 20; iter++)
                {
                    double mid = (low + high) / 2.0;
                    float midAngle = GetForwardRhombusAngle(mid, index);
                    if(Math.Abs(midAngle) < 1e-6) {low = mid; high = mid; break;} // found zero angle
                    double diff = midAngle - angles[i + 1];
                    if (diff > 0)
                        low = mid;
                    else
                        high = mid;
                }
                double refinedT = (low + high) / 2.0;

                angleData.Add((refinedT, index, RhombusForward((float)refinedT, (float)index)));
                // add symmetric angle aswell
                if (refinedT > 0.5)
                {
                    refinedT = 1 - refinedT;
                    angleData.Add((refinedT, index, RhombusForward((float)refinedT, (float)index)));
                }
                else
                {
                    refinedT = 1 - refinedT;
                    angleData.Add((refinedT, index, RhombusForward((float)refinedT, (float)index)));
                }
            }
        }
    }

    private static float GetForwardRhombusAngle(double r, double index)
    {
        // return SpiralCalculator.GetForwardBisectorAngle(r, index);
        return SpiralCalculator.GetInverseReflectedAngle(r, index);
    }

    private static void FindSymmetricIntersections(double index, List<(double real, double index, Vector2 point)> intersectionData)
    {
        // fist low res pass to find approximate path and distances
        const int resolution = 1000;
        double dt = 1.0 / resolution;
        double[] distances = new double[resolution + 1];
        double[] ts = new double[resolution + 1];

        for (int i = 0; i <= resolution; i++)
        {
            double t = i * dt;
            ts[i] = t;
            Vector2 sp = RhombusPoints.GetBPSymmetry((float)t, (float)index);
            Vector2 fp = RhombusForward((float)t, (float)index);
            distances[i] = Vector2.Distance(sp, fp);
        }
    
        // analyze the distance to find when it changes from decreasing to increasing
        // this will give us two points to use for the exact intersection
        for (int i = 0; i < resolution - 1; i++)
        {
            double d0 = distances[i] - distances[i + 1];
            double d1 = distances[i + 1] - distances[i + 2];
            if (d0 > 0 && d1 < 0)
            {
                double low = ts[i];
                double high = ts[i + 2];
                for (int iter = 0; iter < 20; iter++)
                {
                    double mid = (low + high) / 2.0;
                    float midDist = Vector2.Distance(
                        RhombusPoints.GetBPSymmetry((float)mid, (float)index),
                        RhombusForward((float)mid, (float)index)
                    );
                    double diff = midDist - distances[i + 1];
                    if (diff > 0)
                        low = mid;
                    else
                        high = mid;
                }
                // double refinedT = (low + high) / 2.0;
                // Vector2 spFinal = RhombusPoints.GetBPSymmetry((float)refinedT, (float)index);
                // Vector2 fpFinal = RhombusForward((float)refinedT, (float)index);
                // Vector2 avgIntersection = (spFinal + fpFinal) / 2;
                
                // // check false positives
                // if(Vector2.Distance(spFinal, fpFinal) > 0.1f) continue;

                // intersectionData.Add((refinedT, index, avgIntersection));
            
                double refinedT = (low + high) / 2.0f;
                var epsilon = 1e-2;
                double tMin = refinedT - epsilon;
                double tMax = refinedT + epsilon;

                Vector2 fpA = RhombusForward((float)tMin, (float)index);
                Vector2 fpB = RhombusForward((float)tMax, (float)index);
                Vector2 spA = RhombusPoints.GetBPSymmetry((float)tMin, (float)index);
                Vector2 spB = RhombusPoints.GetBPSymmetry((float)tMax, (float)index);

                if (LineSegmentsIntersect(fpA, fpB, spA, spB, out Vector2 intersection))
                {
                    intersectionData.Add((refinedT, index, intersection));
                }
            }
        }
    }

    private static bool LineSegmentsIntersect(Vector2 p1, Vector2 p2, Vector2 q1, Vector2 q2, out Vector2 intersection)
    {
        intersection = Vector2.zero;

        Vector2 r = p2 - p1;
        Vector2 s = q2 - q1;
        float rxs = Cross(r, s);
        float qpxr = Cross(q1 - p1, r);

        if (Math.Abs(rxs) < 1e-8f && Math.Abs(qpxr) < 1e-8f)
            return false; // collinear

        if (Math.Abs(rxs) < 1e-8f)
            return false; // parallel

        float t = Cross(q1 - p1, s) / rxs;
        float u = Cross(q1 - p1, r) / rxs;

        if (t >= 0 && t <= 1 && u >= 0 && u <= 1)
        {
            intersection = p1 + t * r;
            return true;
        }

        return false;
    }

    private static float Cross(Vector2 a, Vector2 b)
    {
        return a.x * b.y - a.y * b.x;
    }

    private static Vector2 RhombusForward(float r, float i)
    {
        // return RhombusPoints.GetBPForward(r, i);
        return RhombusPoints.GetBPReflectedInverse(r, i);
    }

    private static void FindIntersectionsUniformForIndex(double index, List<(double real, double index, Vector2 point)> intersectionData)
    {
        const int resolution = 1000;
        const float INTERSECTION_THRESHOLD = 0.001f;
        double dt = 1.0 / resolution;
        double[] distances = new double[resolution + 1];
        double[] ts = new double[resolution + 1];

        for (int i = 0; i <= resolution; i++)
        {
            double t = i * dt;
            ts[i] = t;
            Vector2 sp = RhombusPoints.GetBPSymmetry((float)t, (float)index);
            Vector2 fp = RhombusPoints.GetBPForward((float)t, (float)index);
            distances[i] = Vector2.Distance(sp, fp);
        }

        for (int i = 0; i < resolution; i++)
        {
            double d0 = distances[i] - INTERSECTION_THRESHOLD;
            double d1 = distances[i + 1] - INTERSECTION_THRESHOLD;
            if (d0 * d1 < 0 || System.Math.Abs(d0) < 1e-6 || System.Math.Abs(d1) < 1e-6)
            {
                double low = ts[i];
                double high = ts[i + 1];
                for (int iter = 0; iter < 20; iter++)
                {
                    double mid = (low + high) / 2.0;
                    float midDist = Vector2.Distance(
                        RhombusPoints.GetBPSymmetry((float)mid, (float)index),
                        RhombusPoints.GetBPForward((float)mid, (float)index)
                    );
                    double diff = midDist - INTERSECTION_THRESHOLD;
                    if (System.Math.Abs(diff) < 1e-6) { low = mid; high = mid; break; }
                    if (diff > 0)
                        low = mid;
                    else
                        high = mid;
                }
                double refinedT = (low + high) / 2.0;
                double epsilon = 1e-5;
                Vector2 sym1 = RhombusPoints.GetBPSymmetry((float)(refinedT - epsilon), (float)index);
                Vector2 sym2 = RhombusPoints.GetBPSymmetry((float)(refinedT + epsilon), (float)index);
                Vector2 forward1 = RhombusPoints.GetBPForward((float)(refinedT - epsilon), (float)index);
                Vector2 forward2 = RhombusPoints.GetBPForward((float)(refinedT + epsilon), (float)index);
                Vector2 exactIntersection;
                if (TryGetLineIntersection(sym1, sym2, forward1, forward2, out exactIntersection))
                {
                    intersectionData.Add((refinedT, index, exactIntersection));
                }
                else
                {
                    Vector2 spFinal = RhombusPoints.GetBPSymmetry((float)refinedT, (float)index);
                    Vector2 fpFinal = RhombusPoints.GetBPForward((float)refinedT, (float)index);
                    Vector2 avgIntersection = (spFinal + fpFinal) / 2;
                    intersectionData.Add((refinedT, index, avgIntersection));
                }
            }
        }
    }
}